class CategoryService {
  var categories = [
    {
      "category": "Tiefkühlkost",
      "products": [
        {"name": "Twinni Eis", "category": "Tiefkühlkost"},
        {"name": "Jolly Eis", "category": "Tiefkühlkost"},
        {"name": "Magnum Classic", "category": "Tiefkühlkost"},
        {"name": "Magnum Pistazie", "category": "Tiefkühlkost"},
        {"name": "Magnum Mandel", "category": "Tiefkühlkost"},
        {"name": "Vanille Eis", "category": "Tiefkühlkost"},
        {"name": "Cornetto", "category": "Tiefkühlkost"},
        {"name": "Erdbeer Combino", "category": "Tiefkühlkost"},
        {"name": "Brickerl Eis", "category": "Tiefkühlkost"},
        {"name": "Tiefkühlpizza", "category": "Tiefkühlkost"},
        {"name": "Pommes Frites", "category": "Tiefkühlkost"},
        {"name": "Wedges", "category": "Tiefkühlkost"},
        {"name": "Kroketten", "category": "Tiefkühlkost"},
        {"name": "Röstinchen", "category": "Tiefkühlkost"},
        {"name": "Blattspinat", "category": "Tiefkühlkost"},
        {"name": "Germknödel", "category": "Tiefkühlkost"},
        {"name": "Erdbeerknödel", "category": "Tiefkühlkost"},
        {"name": "Mohr im Hemd", "category": "Tiefkühlkost"},
        {"name": "Semmelknödel", "category": "Tiefkühlkost"},
        {"name": "Leberknödel", "category": "Tiefkühlkost"},
        {"name": "Gemüse tiefgefroren", "category": "Tiefkühlkost"},
        {"name": "Erbsen tiefgefroren", "category": "Tiefkühlkost"},
        {"name": "Petersilie tiefgefroren", "category": "Tiefkühlkost"},
        {"name": "Kohlsprossen tiefgefroren", "category": "Tiefkühlkost"},
        {"name": "Fisolen tiefgefroren", "category": "Tiefkühlkost"},
        {"name": "Rotkraut tiefgefroren", "category": "Tiefkühlkost"},
        {"name": "Beeren-Mix", "category": "Tiefkühlkost"},
        {"name": "Piccolinis", "category": "Tiefkühlkost"},
        {"name": "Lasagne tiefgefroren", "category": "Tiefkühlkost"},
        {"name": "Eiswürfel", "category": "Tiefkühlkost"}
      ]
    },
    {
      "category": "Spirituosen",
      "products": [
        {"name": "Bier", "category": "Spirituosen"},
        {"name": "Flasche Bier", "category": "Spirituosen"},
        {"name": "Kiste Bier", "category": "Spirituosen"},
        {"name": "Dose Bier", "category": "Spirituosen"},
        {"name": "Weizenbier", "category": "Spirituosen"},
        {"name": "Radler", "category": "Spirituosen"},
        {"name": "Cider", "category": "Spirituosen"},
        {"name": "Prosecco", "category": "Spirituosen"},
        {"name": "Jack Daniel's", "category": "Spirituosen"},
        {"name": "Eristoff Ice", "category": "Spirituosen"},
        {"name": "Eristoff Fire", "category": "Spirituosen"},
        {"name": "Eristoff Flash", "category": "Spirituosen"},
        {"name": "Wein", "category": "Spirituosen"},
        {"name": "Weißwein", "category": "Spirituosen"},
        {"name": "Rotwein", "category": "Spirituosen"},
        {"name": "Roséwein", "category": "Spirituosen"},
        {"name": "Süßwein", "category": "Spirituosen"},
        {"name": "Sekt", "category": "Spirituosen"},
        {"name": "Wodka", "category": "Spirituosen"},
        {"name": "Rum", "category": "Spirituosen"},
        {"name": "Gin", "category": "Spirituosen"},
        {"name": "Tequila", "category": "Spirituosen"},
        {"name": "Whiskey", "category": "Spirituosen"},
        {"name": "Bacardi", "category": "Spirituosen"},
        {"name": "Captain Morgan", "category": "Spirituosen"},
        {"name": "Champagner", "category": "Spirituosen"},
        {"name": "Eierlikör", "category": "Spirituosen"},
        {"name": "Met", "category": "Spirituosen"},
        {"name": "Martini", "category": "Spirituosen"},
        {"name": "Grüner Veltliner", "category": "Spirituosen"},
        {"name": "Chardonnay", "category": "Spirituosen"},
        {"name": "Welschriesling", "category": "Spirituosen"},
        {"name": "Stolichnaya Vodka", "category": "Spirituosen"},
        {"name": "Absolut Vodka", "category": "Spirituosen"},
        {"name": "Jim Beam", "category": "Spirituosen"},
        {"name": "Baileys", "category": "Spirituosen"},
        {"name": "Malibu Kokoslikör", "category": "Spirituosen"},
        {"name": "Aperol", "category": "Spirituosen"},
        {"name": "Jägermeister", "category": "Spirituosen"},
        {"name": "Marillen Likör", "category": "Spirituosen"}
      ]
    },
  ];
}

final CategoryService categoryService = CategoryService();
